site_name: GRAIN - Documentation
site_description: Global Registry of Agricultural Irrigation Networks
repo_url: https://github.com/UW-SASWE/GRAIN
theme:
  name: material  
  palette:
        # Palette toggle for light mode
    - scheme: default
      primary: lime
      accent: indigo
      toggle:
        icon: material/weather-night 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: white
      accent: green
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.footer
  

nav:
  - Home: index.md
  - GRAIN Methodology: grain_methodology.md
  - Reproducing GRAIN Workflow: reproducing_grain_workflow.md
  - Data Structure and Schema: pipeline.md
  - Reading GRAIN Data: reading_grain_data.md
  - Disclaimer: disclaimer.md
  # - Data Sources: data_sources.md
  # - Model: model.md
  # - Validation: validation.md
  # - Examples: examples.md
plugins:
  - search
  # Optional (nice for notebooks):
  # - mkdocs-jupyter
markdown_extensions:
  - attr_list
  - tables
  - admonition
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.keys
  - toc:
      permalink: true

extra:
  analytics:
    provider: google
    property: G-TVNFWF3VZ0
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/SarathUW
      name: GitHub

    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/sarathsuresh96/
      name: LinkedIn
copyright: 'Written and maintained by <a href="https://www.linkedin.com/in/sarathsuresh96/" target="_blank"><b>Sarath Suresh</b>, University of Washington</a>'
